name: samudra
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.13
  - pip=24.2
  - pip:
    - numpy==1.24.4
    - matplotlib==3.8.3
    - xarray==2023.7.0
    - zarr==2.16.1
    - ipykernel==6.29.3
    - cartopy==0.23.0
    - xarrayutils==2.0.1
    - dacite==1.9.1
    - dask==2024.2.1
    - pandas==2.2.1
    - cmocean==4.0.3
    - torch==2.2.1
    - scikit-learn==1.4.1.post1
    - huggingface-hub==0.23.4
    - ipywidgets==8.1.2
    - requests==2.32.3
    - aiohttp==3.9.3
    - cftime>=1.5.2
    - einops==0.8.0
    - nc-time-axis==1.4.1